apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

