apiVersion: v1
kind: Pod
metadata:
    name: nginx-server
    labels:
        app: nginx-server
spec:
    containers:
        - image:
            nginx-server
          imagePullPolicy: Never
          name: nginx-server
          ports:
              - containerPort: 443
              - containerPort: 22
              - containerPort: 80

