apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx-container
          imagePullPolicy: Never
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
            - containerPort: 22
              protocol: TCP
