apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 32443
      #    - port: 80
      #      name: "port2"
      #      protocol: TCP
      #      targetPort: 80
      #      nodePort: 32001
      # - port: 22
      #name: "port3"
      #protocol: TCP
      #targetPort: 22
      #nodePort: 30002

