apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 443
      name: port-https
      protocol: TCP
      targetPort: 443
    - port: 80
      name: port-http
      protocol: TCP
      targetPort: 80
    - port: 22
      name: port-ssh
      protocol: TCP
      targetPort: 22

